# Generated by Django 2.2.12 on 2020-05-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='Description',
        ),
        migrations.AlterField(
            model_name='project',
            name='images',
            field=models.ImageField(upload_to='portfolio/iamge'),
        ),
    ]
